services:

  rabbitmq:
    image: rabbitmq:3-alpine
    networks: [poc_net]
    deploy:
      placement:
        constraints: [node.role == manager]

  provisioner:
    image: poc2:latest
    command: python provisioner.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    networks: [poc_net]
    deploy:
      placement:
        constraints: [node.role == manager]

  event-logger:
    image: poc2:latest
    command: python event_logger.py
    networks: [poc_net]

networks:
  poc_net:
    driver: overlay